import type { Metadata } from "next";
import {
  Averia_Libre,
  Geist,
  Geist_Mono,
  Plus_Jakarta_Sans,
  Montserrat,
  Manrope,
  Inter,
  Lato,
} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/common/Navbar";
import StoreProvider from "./StoreProvider";
import { useAppSelector } from "@/lib/hooks";
import { pageOverflowSelector } from "@/lib/features/application/applicationSelector";
import { InnerLayout } from "./InnerLayout";
import { Toaster } from "@/components/ui/Sonnet";
import PageTransition from "./(site)/PageTransition";
import { CursorRing } from "@/components/common/CursorRing";
import { CursorRingWp } from "@/components/common/CursorRingWp";
import { Footer } from "@/components/common/Footer";

const jakarta = Plus_Jakarta_Sans({
  // weight: "400",
  // subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "BEYOND",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <StoreProvider>
          <Toaster richColors position="top-right" duration={1500} />
          <CursorRing />

          <div className="min-h-dvh flex flex-col select-none bg-ui-bg">
            <Navbar />
            <main className="flex-1 mb-10">{children}</main>
            <Footer />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
