import type { Metadata } from "next";
import { Navbar } from "@/components/common/Navbar";
import { Toaster } from "@/components/ui/Sonnet";
import { CursorRing } from "@/components/common/CursorRing";
import { CursorRingWp } from "@/components/common/CursorRingWp";
import { Footer } from "@/components/common/Footer";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "../StoreProvider";
import { getMessages } from "next-intl/server";
import { SnowParticles } from "@/components/common/SnowParticles";
import { LanguageSwitcher } from "@/components/common/LanguageSwitcher";

export const metadata: Metadata = {
  title: "BEYOND",
  // description: "Generated by create next app",
  metadataBase: new URL("https://groupebeyond.com"),
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages({ locale });

  return (
    <StoreProvider>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Toaster richColors position="top-right" duration={1500} />
        <SnowParticles count={32} />
        <LanguageSwitcher />
        <CursorRing />

        <div className="min-h-dvh w-full overflow-x-hidden flex flex-col bg-ui-bg">
          <Navbar />
          <main className="flex-1 mb-10 w-full">{children}</main>
          <Footer />
        </div>
      </NextIntlClientProvider>
    </StoreProvider>
  );
}
